### ISSUE TITLE
Drawing scaling doesnt work and doesnt load properly

### ISSUE THREAD

**Issue by DeltaRule** [DeltaRule/NoteDawg#1]
* The Dragging thingy doesnt load properly and is somewhere to be seen
* If loading a new canvas the colorbar doesnt load
* strg+z need prevent default
* rightclick needs to create straight lines in chromium browsers aswell (prevent default)
* The scaling of the canvas ist a little bit scuffed

**Comment by Pitti11** [comment]
fixed by #[160b2b9](https://github.com/DeltaRule/NoteDawg/commit/160b2b9917b1be0e1de0e1e826725cb85607cd67)
